# CMake generated Testfile for 
# Source directory: /src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2
# Build directory: /src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GTK2Components.gtk "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gtk" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Components/gtk" "--build-generator" "Unix Makefiles" "--build-target" "gtk-all-libs" "--build-project" "gtk" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Components/gtk" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.glib "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/glib" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/glib" "--build-generator" "Unix Makefiles" "--build-project" "glib" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/glib" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gobject "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gobject" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gobject" "--build-generator" "Unix Makefiles" "--build-project" "gobject" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gobject" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gio "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gio" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gio" "--build-generator" "Unix Makefiles" "--build-project" "gio" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gio" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gmodule "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gmodule" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gmodule" "--build-generator" "Unix Makefiles" "--build-project" "gmodule" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gmodule" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gthread "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gthread" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gthread" "--build-generator" "Unix Makefiles" "--build-project" "gthread" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gthread" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.atk "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/atk" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/atk" "--build-generator" "Unix Makefiles" "--build-project" "atk" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/atk" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gdk_pixbuf "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gdk_pixbuf" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--build-generator" "Unix Makefiles" "--build-project" "gdk_pixbuf" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.cairo "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/cairo" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/cairo" "--build-generator" "Unix Makefiles" "--build-project" "cairo" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/cairo" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.pango "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/pango" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pango" "--build-generator" "Unix Makefiles" "--build-project" "pango" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pango" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.pangocairo "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/pangocairo" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangocairo" "--build-generator" "Unix Makefiles" "--build-project" "pangocairo" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangocairo" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.pangoxft "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/pangoxft" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangoxft" "--build-generator" "Unix Makefiles" "--build-project" "pangoxft" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangoxft" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.pangoft2 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/pangoft2" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangoft2" "--build-generator" "Unix Makefiles" "--build-project" "pangoft2" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/pangoft2" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gdk "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gdk" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gdk" "--build-generator" "Unix Makefiles" "--build-project" "gdk" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gdk" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
add_test(GTK2Targets.gtk "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "--build-and-test" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/gtk" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gtk" "--build-generator" "Unix Makefiles" "--build-project" "gtk" "--build-exe-dir" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/FindGTK2/GTK2Targets/gtk" "--force-new-ctest-process" "--test-command" "/src/app/kubeDimension/tools/CMake-3.4.0/bin/ctest" "-V")
