/*
 * Generated by /src/app/kubeDimension/include/HyperTable/htbuild-dir/cmake-2.6.4/bootstrap
 * Version:     $Revision: 1.113.2.1 $
 *
 * Source directory: /src/app/kubeDimension/include/HyperTable/htbuild-dir/cmake-2.6.4
 * Binary directory: /src/app/kubeDimension/include/HyperTable/htbuild-dir/cmake-2.6.4/Bootstrap.cmk
 *
 * C compiler:   cc
 * C flags:      
 *
 * C++ compiler: g++
 * C++ flags:    
 *
 * Make:         make
 *
 * Sources:
 *   cmake    cmakemain   cmakewizard    cmCommandArgumentLexer   cmCommandArgumentParser   cmCommandArgumentParserHelper   cmDepends   cmDependsC   cmDocumentationFormatter   cmDocumentationFormatterText   cmPolicies   cmProperty   cmPropertyMap   cmPropertyDefinition   cmPropertyDefinitionMap   cmMakeDepend   cmMakefile   cmExportFileGenerator   cmExportInstallFileGenerator   cmInstallDirectoryGenerator   cmGeneratedFileStream   cmGlobalGenerator   cmLocalGenerator   cmInstallGenerator   cmInstallExportGenerator   cmInstallFilesGenerator   cmInstallScriptGenerator   cmInstallTargetGenerator   cmSourceFile   cmSourceFileLocation   cmSystemTools   cmVersion   cmFileTimeComparison   cmGlobalUnixMakefileGenerator3   cmLocalUnixMakefileGenerator3   cmMakefileExecutableTargetGenerator   cmMakefileLibraryTargetGenerator   cmMakefileTargetGenerator   cmMakefileUtilityTargetGenerator   cmBootstrapCommands   cmCommands   cmTarget   cmTest   cmCustomCommand   cmDocumentVariables   cmCacheManager   cmListFileCache   cmComputeLinkDepends   cmComputeLinkInformation   cmOrderDirectories   cmComputeTargetDepends   cmComputeComponentGraph   cmExprLexer   cmExprParser   cmExprParserHelper    cmListFileLexer   
 * kwSys Sources:
 *   Directory   Glob   RegularExpression   SystemTools     ProcessUNIX     String     System 
 */

/* #undef CMAKE_NO_STD_NAMESPACE */
/* #undef CMAKE_NO_ANSI_STREAM_HEADERS */
/* #undef CMAKE_NO_ANSI_STRING_STREAM */
/* #undef CMAKE_NO_ANSI_FOR_SCOPE */
#define CMake_VERSION_MAJOR 2
#define CMake_VERSION_MINOR 6
#define CMake_VERSION_PATCH 4
#define CMAKE_ROOT_DIR "/src/app/kubeDimension/include/HyperTable/htbuild-dir/cmake-2.6.4"
#define CMAKE_DATA_DIR "/share/cmake-2.6"
#define CMAKE_BOOTSTRAP
