/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FaceDetectJNI_FaceDetectBR */

#ifndef _Included_FaceDetectJNI_FaceDetectBR
#define _Included_FaceDetectJNI_FaceDetectBR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FaceDetectJNI_FaceDetectBR
 * Method:    compareResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_FaceDetectJNI_FaceDetectBR_compareResult
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     FaceDetectJNI_FaceDetectBR
 * Method:    initopenBR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FaceDetectJNI_FaceDetectBR_initopenBR
  (JNIEnv *, jobject);

/*
 * Class:     FaceDetectJNI_FaceDetectBR
 * Method:    finishopenBR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FaceDetectJNI_FaceDetectBR_finishopenBR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
