# CMake generated Testfile for 
# Source directory: /src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly
# Build directory: /src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeOnly.LinkInterfaceLoop "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
set_tests_properties(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
add_test(CMakeOnly.CheckSymbolExists "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXSymbolExists "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXCompilerFlag "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckLanguage "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CheckLanguage" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckStructHasMember "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CheckStructHasMember" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdC "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CompilerIdC" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdCXX "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdFortran "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=CompilerIdFortran" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.AllFindModules "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=AllFindModules" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.SelectLibraryConfigurations "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.TargetScope "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=TargetScope" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_library "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=find_library" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_path "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=find_path" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.ProjectInclude "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_2 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_3 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_2 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_3 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_3 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_4 "/src/app/kubeDimension/tools/CMake-3.4.0/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/src/app/kubeDimension/tools/CMake-3.4.0/Tests/CMakeOnly/Test.cmake")
